In [1]:
'''
preprocess feature seletion data
'''

'\npreprocess feature seletion data\n'

In [2]:
import numpy as np
import pandas as pd 
import os 

Read Data

In [4]:
path_dir = './data/feature_selection_test.csv'
df = pd.read_csv(path_dir)
df.head(5)

Username  Mobility ArmSwelling BreastSwelling Skin PAS FHT  DISCOMFORT  \
0    ML380         2           0              2    0   1   0           1   
1    ML381         1           0              0    1   0   0           1   
2    ML382         0           0              0    0   0   0           0   
3    ML383         0           0              0    0   1   3           3   
4    ML384         0           0              0    0   0   0           0   

   SYM_COUNT TIME_LAPSE  ... chemo_numbered Radiation   Age  SLNB_Removed_LN  \
0          5        0.8  ...              1         1  70.0                1   
1          4        2.2  ...              1         1  54.0                2   
2          0        6.3  ...              1         1  70.0                0   
3         10        4.3  ...              1         1  40.0                0   
4          0        3.1  ...              0         1  76.0                1   

   ALND_Removed_LN  SLNB_ALND_Removed  Mastectomy  Lumpectomy  Hormonal   BMI  
0                0                  0           0           1       1.0  39.8  
1                0                  0           0           1       1.0  25.2  
2                0                  7           0           1       1.0  33.8  
3                0                 15           0           1       0.0  21.1  
4                0                  0           0           1       1.0  27.2  

[5 rows x 23 columns]

In [5]:
print('columns:')
print(df.columns)

columns:
Index(['Username', 'Mobility', 'ArmSwelling', 'BreastSwelling', 'Skin', 'PAS',
       'FHT', 'DISCOMFORT', 'SYM_COUNT', 'TIME_LAPSE', 'LVC',
       'ChestWallSwelling', 'fluid_total', 'chemo_numbered', 'Radiation',
       'Age', 'SLNB_Removed_LN', 'ALND_Removed_LN', 'SLNB_ALND_Removed',
       'Mastectomy', 'Lumpectomy', 'Hormonal', 'BMI'],
      dtype='object')


Select Features

In [6]:
data_df = df.rename({'chemo_numbered':'Chemotherapy'}, axis=1)
print('columns:')
print(data_df.columns)
print('shape:')
print(data_df.shape)

columns:
Index(['Username', 'Mobility', 'ArmSwelling', 'BreastSwelling', 'Skin', 'PAS',
       'FHT', 'DISCOMFORT', 'SYM_COUNT', 'TIME_LAPSE', 'LVC',
       'ChestWallSwelling', 'fluid_total', 'Chemotherapy', 'Radiation', 'Age',
       'SLNB_Removed_LN', 'ALND_Removed_LN', 'SLNB_ALND_Removed', 'Mastectomy',
       'Lumpectomy', 'Hormonal', 'BMI'],
      dtype='object')
shape:
(191, 23)


Convert feature value

Data Filtering

In [7]:
# remove specfic data point 
data_df = data_df[data_df.Username != 'ML509']

In [8]:
# fill 0 for missing data
for column in ['Mobility', 'ArmSwelling', 'BreastSwelling', 'Skin', 'ChestWallSwelling', 'Chemotherapy', \
               'Radiation', 'SLNB_Removed_LN', 'ALND_Removed_LN', 'SLNB_ALND_Removed']:
    data_df[column].fillna(0, inplace=True)

In [9]:
data_df = data_df.dropna(subset=['TIME_LAPSE', 'BMI', 'Age', 'LVC'])
print('shape:')
print(data_df.shape)

shape:
(190, 23)


In [10]:
data_df = data_df.apply(lambda x: pd.to_numeric(x, errors='coerce'))
# drop rows containing nan
data_df = data_df.dropna()

In [11]:
data_df[['Mobility', 'ArmSwelling', 'BreastSwelling', 'Skin', 'ChestWallSwelling', 'Chemotherapy', \
               'Radiation', 'SLNB_Removed_LN', 'ALND_Removed_LN', 'SLNB_ALND_Removed']].isnull().values.any()

False

<b> Compare two version of ./data/feature_selection_preprocessed_data.csv <b>

In [4]:
df1 = pd.read_csv('./data/feature_selection_preprocessed_data.csv')
df2 = pd.read_csv('./data/feature_selection_preprocessed_data_12.23.2020.csv')

In [11]:
len(set(df1['Username'].values) & set(df2['Username'].values))

906

In [5]:
df2

Unnamed: 0   Username  Mobility  ArmSwelling  BreastSwelling  Skin  PAS  \
0           0.0  B001_year         1            0               0     0    0   
1           1.0  B002_year         0            2               3     0    0   
2           2.0  B003_year         1            0               0     0    0   
3           3.0  B004_year         0            0               0     0    0   
4           4.0  B005_year         2            1               0     0    2   
..          ...        ...       ...          ...             ...   ...  ...   
905       905.0      ML375         0            0               2     1    2   
906       906.0      ML376         1            0               0     0    0   
907       907.0      ML378         0            0               0     0    0   
908       908.0      ML379         1            0               0     0    0   
909       909.0      ML380         2            0               2     0    1   

     FHT  Neuropathic  SYM_COUNT  ...  Radiation   Age  SLNB_Removed_LN  \
0      1            0          2  ...          0  40.0              1.0   
1      1            1          7  ...          1  63.0              0.0   
2      0            0          1  ...          0  42.0              2.0   
3      1            1          3  ...          1  47.0              5.0   
4      0            2         11  ...          1  33.0              0.0   
..   ...          ...        ...  ...        ...   ...              ...   
905    2            2          9  ...          1  58.0              1.0   
906    0            1          2  ...          1  37.0              0.0   
907    0            0          0  ...          1  50.0              6.0   
908    0            0          1  ...          1  46.0              1.0   
909    0            1          5  ...          1  70.0              1.0   

    ALND_Removed_LN SLNB_ALND_Removed  Number_nodes  Mastectomy  Lumpectomy  \
0               0.0               0.0           1.0           1           0   
1              14.0               0.0          14.0           0           1   
2               0.0               0.0           2.0           1           0   
3               0.0               0.0           5.0           1           0   
4              16.0               0.0          16.0           1           0   
..              ...               ...           ...         ...         ...   
905             0.0               0.0           1.0           0           1   
906            12.0               0.0          12.0           1           0   
907             0.0               0.0           6.0           0           1   
908             0.0               0.0           1.0           0           1   
909             0.0               0.0           1.0           0           1   

     Hormonal   BMI  
0           0  22.1  
1           0  38.7  
2           1  32.6  
3           1  42.6  
4           0  17.4  
..        ...   ...  
905         1  23.5  
906         0  25.3  
907         1  28.0  
908         1  22.7  
909         1  39.8  

[910 rows x 24 columns]

In [14]:
df1.columns

Index(['Unnamed: 0', 'Username', 'Mobility', 'ArmSwelling', 'BreastSwelling',
       'Skin', 'PAS', 'FHT', 'DISCOMFORT', 'SYM_COUNT', 'TIME_LAPSE', 'LVC',
       'ChestWallSwelling', 'fluid_total', 'Chemotherapy', 'Radiation', 'Age',
       'SLNB_Removed_LN', 'ALND_Removed_LN', 'SLNB_ALND_Removed',
       'Number_nodes', 'Mastectomy', 'Lumpectomy', 'Hormonal', 'BMI'],
      dtype='object')

In [15]:
df2.columns

Index(['Unnamed: 0', 'Username', 'Mobility', 'ArmSwelling', 'BreastSwelling',
       'Skin', 'PAS', 'FHT', 'Neuropathic', 'SYM_COUNT', 'TIME_LAPSE', 'LVC',
       'ChestWallSwelling', 'Chemotherapy', 'Radiation', 'Age',
       'SLNB_Removed_LN', 'ALND_Removed_LN', 'SLNB_ALND_Removed',
       'Number_nodes', 'Mastectomy', 'Lumpectomy', 'Hormonal', 'BMI',
       'Unnamed: 24', 'Unnamed: 25'],
      dtype='object')

In [24]:
df2.rename(columns={'Neuropathic':'DISCOMFORT'})

Unnamed: 0   Username  Mobility  ArmSwelling  BreastSwelling  Skin  PAS  \
0           0.0  B001_year         1            0               0     0    0   
1           1.0  B002_year         0            2               3     0    0   
2           2.0  B003_year         1            0               0     0    0   
3           3.0  B004_year         0            0               0     0    0   
4           4.0  B005_year         2            1               0     0    2   
..          ...        ...       ...          ...             ...   ...  ...   
905       905.0      ML375         0            0               2     1    2   
906       906.0      ML376         1            0               0     0    0   
907       907.0      ML378         0            0               0     0    0   
908       908.0      ML379         1            0               0     0    0   
909       909.0      ML380         2            0               2     0    1   

     FHT  DISCOMFORT  SYM_COUNT  ...  SLNB_Removed_LN ALND_Removed_LN  \
0      1           0          2  ...              1.0             0.0   
1      1           1          7  ...              0.0            14.0   
2      0           0          1  ...              2.0             0.0   
3      1           1          3  ...              5.0             0.0   
4      0           2         11  ...              0.0            16.0   
..   ...         ...        ...  ...              ...             ...   
905    2           2          9  ...              1.0             0.0   
906    0           1          2  ...              0.0            12.0   
907    0           0          0  ...              6.0             0.0   
908    0           0          1  ...              1.0             0.0   
909    0           1          5  ...              1.0             0.0   

     SLNB_ALND_Removed Number_nodes Mastectomy  Lumpectomy  Hormonal   BMI  \
0                  0.0          1.0          1           0         0  22.1   
1                  0.0         14.0          0           1         0  38.7   
2                  0.0          2.0          1           0         1  32.6   
3                  0.0          5.0          1           0         1  42.6   
4                  0.0         16.0          1           0         0  17.4   
..                 ...          ...        ...         ...       ...   ...   
905                0.0          1.0          0           1         1  23.5   
906                0.0         12.0          1           0         0  25.3   
907                0.0          6.0          0           1         1  28.0   
908                0.0          1.0          0           1         1  22.7   
909                0.0          1.0          0           1         1  39.8   

     Unnamed: 24  Unnamed: 25  
0            NaN          NaN  
1            NaN          NaN  
2            NaN          NaN  
3            NaN          NaN  
4            NaN          NaN  
..           ...          ...  
905          NaN          NaN  
906          NaN          NaN  
907          NaN          NaN  
908          NaN          NaN  
909          NaN          NaN  

[910 rows x 26 columns]

In [17]:
[x for x in df2['Username'].values if x not in set(df1['Username'].values)]

['A001', 'T001', 'T005', 'T016']

<b> Combine all three dataset and divide it to train/test<b>

In [1]:
import numpy as np
import pandas as pd 
import os 
from expert_tree import get_expert_tree_results, Expert_Tree

In [2]:
csvs = ['./data/feature_selection_preprocessed_data_12.23.2020.csv', './data/feature_selection_test.csv', './data/feature_selection_kinect_test.csv']
pds = [pd.read_csv(csv) for csv in csvs]
print('data included:', csvs)

data included: ['./data/feature_selection_preprocessed_data_12.23.2020.csv', './data/feature_selection_test.csv', './data/feature_selection_kinect_test.csv']


process feature_selection_preprocessed_data.csv

In [3]:
delete_rows = ['A001', 'A003', 'A004', 'A005', 'A015', 'A016',
               'A018', 'A025', 'A026', 'A029', 'A031', 'A032',
               'A035', 'A036', 'A038', 'A042', 'A046', 'A055',
               'T010', 'T013', 'T014', 'T016', 'T018', 'T019',
               'T021', 'T026', 'T029', 'T030', 'T036', 'T038',
               'T040', 'T043', 'T044', 'T054', 'T055', 'T056',
               'T057'] 

data = pds[0]
# change back name 
data=data.rename(columns={'Neuropathic':'DISCOMFORT'})
#data = data.drop(columns=['Unnamed: 24', 'Unnamed: 25'])

# drop list of subjects
data = data[~data.Username.isin(delete_rows)]
# drop data within a 6 months
data = data[data.TIME_LAPSE >=0.5]
data = data.drop(columns=['Unnamed: 0'])

# add log of time elapsed
data['TIME_LAPSE_LOG'] = np.log(data['TIME_LAPSE'])

# the data_pre contain '#DEV/0!' or "" to make the coloumn string instead of float
# and these dirty element would cause error in .astype operation
# here convert "" or  '#DEV/0!' to nan
data.iloc[:,1:] = data.iloc[:,1:].apply(lambda x: pd.to_numeric(x, errors='coerce'))

# drop rows containing nan
data = data.dropna()

# generate three class label 
labels_3, _, flags1 = get_expert_tree_results(data, is_Kinect=False, class_number=3)
print(np.unique(labels_3, return_counts=True))


data["3class_label"] = labels_3

# drop LVC and time time elapse
data = data.drop(columns=['LVC', 'TIME_LAPSE'])
data = data.drop(columns=['Number_nodes'])
print('shape:')
print(data.shape)

pds[0] = data

(array([0, 1, 2]), array([443, 150, 266]))
shape:
(859, 22)


process feature_selection_test.csv

In [4]:
np.unique(pds[1]['Hormonal'].values)

array([ 0.,  1., nan])

In [5]:
data = pds[1]

data = data.rename({'chemo_numbered':'Chemotherapy'}, axis=1)
# remove specfic data point 
data = data[data.Username != 'ML509']
# fill 0 for missing data
for column in ['Mobility', 'ArmSwelling', 'BreastSwelling', 'Skin', 'ChestWallSwelling', 'Chemotherapy', \
               'Radiation', 'SLNB_Removed_LN', 'ALND_Removed_LN', 'SLNB_ALND_Removed']:
    data[column].fillna(0, inplace=True)
# drop data missing important feature
data = data.dropna(subset=['TIME_LAPSE', 'BMI', 'Age', 'LVC'])
# delete Username
#data = data.drop(columns='Username')
# convert string to float
#data_test = data_test.apply(lambda x: pd.to_numeric(x, errors='coerce'))
data.iloc[:,1:] = data.iloc[:,1:].astype(np.float64)
# drop rows containing nan
data = data.dropna()
# drop data within a 6 months
data = data[data.TIME_LAPSE >=0.5]
# add log of time elapsed
data['TIME_LAPSE_LOG'] = np.log(data['TIME_LAPSE'])

#print('shape:')
#print(data.shape)

# generate three class label 
labels_3, _, flags2 = get_expert_tree_results(data, is_Kinect=False, class_number=3)
print(np.unique(labels_3, return_counts=True))

data["3class_label"] = labels_3

# drop LVC and time time elapse
data = data.drop(columns=['LVC', 'TIME_LAPSE', 'fluid_total'])
print('shape:')
print(data.shape)

pds[1] = data


(array([0, 1, 2]), array([134,  15,  27]))
shape:
(176, 22)


In [6]:
[flag for flag in flags2 if 'u' in flag]

[]

process feature_selection_kinect_test

In [7]:
np.unique(pds[1]['Hormonal'].values)

array([0., 1.])

In [8]:
data = pds[2]
# drop data within a 6 months
data = data[data.TIME_LAPSE >=0.5]
# data = data.drop(columns=['Username'])

# add log of time elapsed
data['TIME_LAPSE_LOG'] = np.log(data['TIME_LAPSE'])

# the data_pre contain '#DEV/0!' or "" to make the coloumn string instead of float
# and these dirty element would cause error in .astype operation
# here convert "" or  '#DEV/0!' to nan
#data.iloc[:,1:] = data.iloc[:,1:].apply(lambda x: pd.to_numeric(x, errors='coerce'))
data.iloc[:,1:] = data.iloc[:,1:].astype(np.float64)
# drop rows containing nan
data = data.dropna()

# generate three class label 
labels_3, _, flags3 = get_expert_tree_results(data, is_Kinect=True, class_number=3)
print(np.unique(labels_3, return_counts=True))

data["3class_label"] = labels_3

# drop LVC and time time elapse
data = data.drop(columns=['LVC', 'TIME_LAPSE', 'fluid_total'])
data = data.drop(columns=['Number_nodes'])
print('shape:')
print(data.shape)

pds[2] = data

(array([0, 1, 2]), array([ 6,  6, 18]))
shape:
(30, 22)


<ipython-input-8-3f251283c6ef>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['TIME_LAPSE_LOG'] = np.log(data['TIME_LAPSE'])
/scratch/jc7489/anaconda3/envs/research/lib/python3.8/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


In [9]:
[flag for flag in flags3 if 'u' in flag]

[]

merge 3 dataset

In [10]:
merged_data = pd.concat(pds, axis=0)
print("shape")
print(merged_data.shape)
merged_data = merged_data.set_index('Username')
merged_data = merged_data.drop_duplicates()

shape
(1065, 22)


In [11]:
labels = merged_data['3class_label'].values

In [12]:
values, counts = np.unique(labels, return_counts=True)
print(values)
print(counts)
ratios = counts / len(labels)
print(ratios)

[0 1 2]
[583 170 311]
[0.54793233 0.15977444 0.29229323]


Final Process:  if a patient has both Lumpectomy=1 and Mastectomy=1, we consider it Mastecotomy=1 and Lumpectomy=0

In [13]:
merged_data.loc[(merged_data['Lumpectomy']==1) & (merged_data['Mastectomy']==1), 'Lumpectomy'] = 0

In [14]:
merged_data[(merged_data['Lumpectomy']==1) & (merged_data['Mastectomy']==1)].shape

(0, 21)

In [15]:
merged_data.to_csv('./data/result_data/whole_dataset_Dec23_.csv')

Check Hormonal 

In [16]:
np.unique(merged_data['Hormonal'].values)

array([0., 1.])

Divide Train and Validation

In [17]:
train = pd.read_csv('./data/result_data/split_train_Oct21_stratified.csv')
test = pd.read_csv('./data/result_data/split_test_Oct21_stratified.csv')

In [21]:
train_new = merged_data.loc[list(train['Username'].values)]
test_new = merged_data.loc[list(test['Username'].values)]

In [68]:
train_new.to_csv('./data/result_data/split_train_Dec23_stratified.csv')
test_new.to_csv('./data/result_data/split_test_Dec23_stratified.csv')

In [19]:
d = list(train['Username'].values) + list(test['Username'].values)
[x for x in d if x not in merged_data.index.values]

[]

In [31]:
for feat in train_new.columns:
    print(feat)
    print(all(train[feat].values == train_new[feat].values))

Mobility
True
ArmSwelling
True
BreastSwelling
True
Skin
True
PAS
True
FHT
True
DISCOMFORT
True
SYM_COUNT
True
ChestWallSwelling
True
Chemotherapy
True
Radiation
True
Age
True
SLNB_Removed_LN
True
ALND_Removed_LN
False
SLNB_ALND_Removed
False
Mastectomy
False
Lumpectomy
False
Hormonal
False
BMI
True
TIME_LAPSE_LOG
False
3class_label
True


In [64]:
feat ='TIME_LAPSE_LOG'
idx = train[feat].values == train_new[feat].values

In [65]:
a1 = train[feat][~idx].values

In [66]:
a2 = train_new[feat][~idx].values

In [67]:
a1 - a2

array([-4.44089210e-16,  4.44089210e-16,  4.44089210e-16,  4.44089210e-16,
        2.22044605e-16,  2.22044605e-16,  4.44089210e-16, -4.44089210e-16,
        1.11022302e-16, -2.22044605e-16, -5.55111512e-17,  4.44089210e-16,
       -5.55111512e-17, -1.38777878e-17,  2.22044605e-16, -1.38777878e-17,
       -1.38777878e-17, -2.22044605e-16,  1.11022302e-16, -5.55111512e-17,
       -2.22044605e-16, -1.38777878e-17, -2.22044605e-16,  4.44089210e-16,
       -4.44089210e-16,  4.44089210e-16,  2.22044605e-16, -4.44089210e-16,
        2.22044605e-16, -6.66133815e-16, -2.22044605e-16, -1.38777878e-17,
        2.22044605e-16,  2.22044605e-16, -2.22044605e-16, -4.44089210e-16,
       -2.22044605e-16,  2.22044605e-16, -4.44089210e-16, -2.22044605e-16,
        4.44089210e-16, -1.38777878e-17,  1.11022302e-16, -2.22044605e-16,
       -4.44089210e-16, -2.22044605e-16, -1.38777878e-17,  1.11022302e-16,
       -2.22044605e-16, -4.44089210e-16, -2.22044605e-16,  6.66133815e-16,
        4.44089210e-16, -

In [69]:
pd.read_csv('./data/result_data/split_train_Dec23_stratified.csv')

Username  Mobility  ArmSwelling  BreastSwelling  Skin  PAS  FHT  \
0    B001_year       1.0          0.0             0.0   0.0  0.0  1.0   
1    B002_year       0.0          2.0             3.0   0.0  0.0  1.0   
2    B003_year       1.0          0.0             0.0   0.0  0.0  0.0   
3    B004_year       0.0          0.0             0.0   0.0  0.0  1.0   
4    B005_year       2.0          1.0             0.0   0.0  2.0  0.0   
..         ...       ...          ...             ...   ...  ...  ...   
881       K017       1.0          1.0             1.0   0.0  1.0  1.0   
882       K018       3.0          1.0             4.0   0.0  3.0  3.0   
883       K023       2.0          1.0             1.0   0.0  1.0  1.0   
884       K029       2.0          3.0             2.0   0.0  2.0  2.0   
885       K030       1.0          1.0             0.0   0.0  0.0  1.0   

     DISCOMFORT  SYM_COUNT  ChestWallSwelling  ...   Age  SLNB_Removed_LN  \
0           0.0        2.0                0.0  ...  40.0              1.0   
1           1.0        7.0                0.0  ...  63.0              0.0   
2           0.0        1.0                0.0  ...  42.0              2.0   
3           1.0        3.0                0.0  ...  47.0              5.0   
4           2.0       11.0                1.0  ...  33.0              0.0   
..          ...        ...                ...  ...   ...              ...   
881         1.0       11.0                0.0  ...  65.0              0.0   
882         3.0       15.0                0.0  ...  48.0              1.0   
883         1.0        8.0                0.0  ...  60.0              3.0   
884         2.0       13.0                2.0  ...  49.0              3.0   
885         1.0        7.0                0.0  ...  54.0              0.0   

     ALND_Removed_LN  SLNB_ALND_Removed  Mastectomy  Lumpectomy  Hormonal  \
0                0.0                0.0         1.0         0.0       0.0   
1               14.0                0.0         0.0         1.0       0.0   
2                0.0                0.0         1.0         0.0       1.0   
3                0.0                0.0         1.0         0.0       1.0   
4               16.0                0.0         1.0         0.0       0.0   
..               ...                ...         ...         ...       ...   
881              0.0               15.0         1.0         0.0       0.0   
882              0.0                0.0         0.0         1.0       0.0   
883              0.0                0.0         0.0         1.0       0.0   
884              0.0                0.0         1.0         0.0       1.0   
885             12.0                0.0         0.0         0.0       0.0   

      BMI  TIME_LAPSE_LOG  3class_label  
0    22.1        0.000000             0  
1    38.7        0.000000             2  
2    32.6        0.000000             0  
3    42.6        0.000000             0  
4    17.4        0.000000             2  
..    ...             ...           ...  
881  16.0        2.708050             2  
882  24.9        1.098612             2  
883  32.5        1.386294             2  
884  37.3        1.791759             2  
885  31.5        2.197225             1  

[886 rows x 22 columns]

In [70]:
pd.read_csv('./data/result_data/split_train_Oct21_stratified.csv')

Unnamed: 0   Username  Mobility  ArmSwelling  BreastSwelling  Skin  PAS  \
0             0  B001_year       1.0          0.0             0.0   0.0  0.0   
1             1  B002_year       0.0          2.0             3.0   0.0  0.0   
2             2  B003_year       1.0          0.0             0.0   0.0  0.0   
3             3  B004_year       0.0          0.0             0.0   0.0  0.0   
4             4  B005_year       2.0          1.0             0.0   0.0  2.0   
..          ...        ...       ...          ...             ...   ...  ...   
881        1051       K017       1.0          1.0             1.0   0.0  1.0   
882        1052       K018       3.0          1.0             4.0   0.0  3.0   
883        1057       K023       2.0          1.0             1.0   0.0  1.0   
884        1063       K029       2.0          3.0             2.0   0.0  2.0   
885        1064       K030       1.0          1.0             0.0   0.0  0.0   

     FHT  DISCOMFORT  SYM_COUNT  ...   Age  SLNB_Removed_LN  ALND_Removed_LN  \
0    1.0         0.0        2.0  ...  40.0              1.0              0.0   
1    1.0         1.0        7.0  ...  63.0              0.0             14.0   
2    0.0         0.0        1.0  ...  42.0              2.0              0.0   
3    1.0         1.0        3.0  ...  47.0              5.0              0.0   
4    0.0         2.0       11.0  ...  33.0              0.0             16.0   
..   ...         ...        ...  ...   ...              ...              ...   
881  1.0         1.0       11.0  ...  65.0              0.0              0.0   
882  3.0         3.0       15.0  ...  48.0              1.0              0.0   
883  1.0         1.0        8.0  ...  60.0              3.0              0.0   
884  2.0         2.0       13.0  ...  49.0              3.0              0.0   
885  1.0         1.0        7.0  ...  54.0              0.0             12.0   

     SLNB_ALND_Removed  Mastectomy  Lumpectomy  Hormonal   BMI  \
0                  0.0         1.0         0.0       0.0  22.1   
1                  0.0         0.0         1.0       0.0  38.7   
2                  0.0         1.0         0.0       1.0  32.6   
3                  0.0         1.0         0.0       1.0  42.6   
4                  0.0         1.0         0.0       0.0  17.4   
..                 ...         ...         ...       ...   ...   
881               15.0         1.0         0.0       0.0  16.0   
882                0.0         0.0         1.0       0.0  24.9   
883                0.0         0.0         1.0       0.0  32.5   
884                0.0         1.0         0.0       1.0  37.3   
885                0.0         0.0         0.0       0.0  31.5   

     TIME_LAPSE_LOG  3class_label  
0          0.000000             0  
1          0.000000             2  
2          0.000000             0  
3          0.000000             0  
4          0.000000             2  
..              ...           ...  
881        2.708050             2  
882        1.098612             2  
883        1.386294             2  
884        1.791759             2  
885        2.197225             1  

[886 rows x 23 columns]

In [ ]:
Unnamed: 0